=== tastyminerals/coherent-text-generation-limited/training_data/inscript/InScript/corpus/InScript.dtd
<!-- element definitions -->
<!-- root element -->
<!ELEMENT story (text, annotations)>

<!-- the text -->
<!ELEMENT text (content, sentences)>
<!ELEMENT content (#PCDATA)>
<!ELEMENT sentences (sentence*)>
<!ELEMENT sentence (token*)>
<!ELEMENT token (pos?, lemma?, dep?)>
<!ELEMENT pos EMPTY>
<!ELEMENT lemma EMPTY>
<!ELEMENT dep EMPTY>

<!-- annotations -->
<!ELEMENT annotations (participants, events, chains)>
<!ELEMENT participants (label*)>
<!ELEMENT events (label*)>
<!ELEMENT chains (chain*)>
<!ELEMENT label EMPTY>
<!ELEMENT chain EMPTY>


<!-- attribute definitions -->
<!-- root element -->
<!ATTLIST story 
	id			CDATA	#REQUIRED
	scenario	CDATA	#REQUIRED
>

<!-- the text -->
<!ATTLIST sentence id CDATA #REQUIRED>
<!ATTLIST token 
	content	CDATA	#REQUIRED
	id		CDATA	#REQUIRED
>
<!ATTLIST pos type CDATA #REQUIRED>
<!ATTLIST lemma type CDATA #REQUIRED>
<!ATTLIST dep 
	type	CDATA	#REQUIRED
	head	CDATA	#REQUIRED
>
	
<!-- annotations -->
<!ATTLIST label 
	from	CDATA				#REQUIRED
	id		CDATA				#REQUIRED
	name	CDATA				#REQUIRED
	type	(participant|event)	#REQUIRED
	to		CDATA				#IMPLIED
	text	CDATA				#REQUIRED
>
<!ATTLIST chain 
	elements	CDATA	#REQUIRED
	name		CDATA	#IMPLIED
>

=== tastyminerals/coherent-text-generation-limited/training_data/inscript/InScript/corpus/bath/bath_082.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE story SYSTEM "../InScript.dtd">
<story id="082" scenario="bath">
    <text>
        <content>Every morning I take a bath . 
Before I get into the bath tub , I turn on the water . 
I adjust the cold and the hot water to make a bearable temperature . 
I adjust the water before entering the tub so I wo n't burn or freeze myself . 
After the water is just right , I take off all my clothes and enter the tub . 
I pour water on my body then I lather up with either soap or shower gel . 
Once I have soap all over my body , I take my loofah sponge and pour soap on that as well . 
I , then , begin to scrub my body as firm but gently as I can . 
I do this to ensure that all the dirt washes off my skin . 
While I am scrubbing my body , I like to sing in the shower . 
After I scrub really good and finish singing , I pour water continuously on my body until all the soap washes off . 
I stay in the shower for about twenty minutes until I feel clean . </content>
        <sentences>
            <sentence id="1">
                <token content="Every" id="1-1">
                    <pos type="DT"/>
                    <lemma type="every"/>
                </token>
                <token content="morning" id="1-2">
                    <pos type="NN"/>
                    <lemma type="morning"/>
                    <dep head="1-4" type="tmod"/>
                </token>
                <token content="I" id="1-3">
                    <pos type="PRP"/>
                    <lemma type="I"/>
                    <dep head="1-4" type="nsubj"/>
                </token>
                <token content="take" id="1-4">
                    <pos type="VBP"/>
                    <lemma type="take"/>
                </token>
                <token content="a" id="1-5">
                    <pos type="DT"/>
                    <lemma type="a"/>
                </token>
                <token content="bath" id="1-6">
                    <pos type="NN"/>
                    <lemma type="bath"/>
                    <dep head="1-4" type="dobj"/>
                </token>
                <token content="." id="1-7"/>
            </sentence>
            <sentence id="2">
                <token content="Before" id="2-1">
                    <pos type="IN"/>
                    <lemma type="before"/>
                    <dep head="2-3" type="mark"/>
                </token>
                <token content="I" id="2-2">
                    <pos type="PRP"/>
                    <lemma type="I"/>
                    <dep head="2-3" type="nsubj"/>
                </token>
                <token content="get" id="2-3">
                    <pos type="VBP"/>
                    <lemma type="get"/>
                    <dep head="2-10" type="advcl"/>
                </token>
                <token content="into" id="2-4"/>
                <token content="the" id="2-5">
                    <pos type="DT"/>
                    <lemma type="the"/>
                </token>
                <token content="bath" id="2-6">
                    <pos type="NN"/>
                    <lemma type="bath"/>
                </token>
                <token content="tub" id="2-7">
                    <pos type="NN"/>
                    <lemma type="tub"/>
                    <dep head="2-3" type="prep"/>
                </token>
                <token content="," id="2-8"/>
                <token content="I" id="2-9">
                    <pos type="PRP"/>
                    <lemma type="I"/>
                    <dep head="2-10" type="nsubj"/>
                </token>
                <token content="turn" id="2-10">
                    <pos type="VBP"/>
                    <lemma type="turn"/>
                </token>
                <token content="on" id="2-11"/>
                <token content="the" id="2-12">
                    <pos type="DT"/>
                    <lemma type="the"/>
                </token>
                <token content="water" id="2-13">
                    <pos type="NN"/>
                    <lemma type="water"/>
                    <dep head="2-10" type="prep"/>
                </token>
                <token content="." id="2-14"/>
            </sentence>
            <sentence id="3">
                <token content="I" id="3-1">
                    <pos type="PRP"/>
                    <lemma type="I"/>
                    <dep head="3-2" type="nsubj"/>
                </token>
                <token content="adjust" id="3-2">
                    <pos type="VBP"/>
                    <lemma type="adjust"/>
                </token>
                <token content="the" id="3-3">
                    <pos type="DT"/>
                    <lemma type="the"/>
                </token>
                <token content="cold" id="3-4">
                    <pos type="NN"/>
                    <lemma type="cold"/>
                    <dep head="3-2" type="dobj"/>
                </token>
                <token content="and" id="3-5"/>
                <token content="the" id="3-6">
                    <pos type="DT"/>
                    <lemma type="the"/>
                </token>
                <token content="hot" id="3-7">
                    <pos type="JJ"/>
                    <lemma type="hot"/>
                </token>
                <token content="water" id="3-8">
                    <pos type="NN"/>
                    <lemma type="water"/>
                </token>
                <token content="to" id="3-9">
                    <pos type="TO"/>
                    <lemma type="to"/>
                    <dep head="3-10" type="aux"/>
                </token>
                <token content="make" id="3-10">
                    <pos type="VB"/>
                    <lemma type="make"/>
                    <dep head="3-2" type="xcomp"/>
                </token>
                <token content="a" id="3-11">
                    <pos type="DT"/>
                    <lemma type="a"/>
                </token>
                <token content="bearable" id="3-12">
                    <pos type="JJ"/>
                    <lemma type="bearable"/>
                </token>
                <token content="temperature" id="3-13">
                    <pos type="NN"/>
                    <lemma type="temperature"/>
                    <dep head="3-10" type="dobj"/>
                </token>
                <token content="." id="3-14"/>
            </sentence>
            <sentence id="4">
                <token content="I" id="4-1">
                    <pos type="PRP"/>
                    <lemma type="I"/>
                    <dep head="4-2" type="nsubj"/>
                </token>
                <token content="adjust" id="4-2">
                    <pos type="VBP"/>
                    <lemma type="adjust"/>
                </token>
                <token content="the" id="4-3">
                    <pos type="DT"/>
                    <lemma type="the"/>
                </token>
                <token content="water" id="4-4">
                    <pos type="NN"/>
                    <lemma type="water"/>
                    <dep head="4-2" type="dobj"/>
                </token>
                <token content="before" id="4-5"/>
                <token content="entering" id="4-6">
                    <pos type="VBG"/>
                    <lemma type="enter"/>
                    <dep head="4-2" type="prepc"/>
                </token>
                <token content="the" id="4-7">
                    <pos type="DT"/>
                    <lemma type="the"/>
                </token>
                <token content="tub" id="4-8">
                    <pos type="NN"/>
                    <lemma type="tub"/>
                    <dep head="4-6" type="dobj"/>
                </token>
                <token content="so" id="4-9">
                    <pos type="IN"/>
                    <lemma type="so"/>
                    <dep head="4-13" type="mark"/>
                </token>
                <token content="I" id="4-10">
                    <pos type="PRP"/>
                    <lemma type="I"/>
                    <dep head="4-13" type="nsubj"/>
                </token>
                <token content="wo" id="4-11">
                    <pos type="MD"/>
                    <lemma type="will"/>
                    <dep head="4-13" type="aux"/>
                </token>
                <token content="n't" id="4-12">
                    <pos type="RB"/>
                    <lemma type="not"/>
                    <dep head="4-13" type="neg"/>
                </token>
                <token content="burn" id="4-13">
                    <pos type="VB"/>
                    <lemma type="burn"/>
                    <dep head="4-6" type="advcl"/>
                </token>
                <token content="or" id="4-14"/>
                <token content="freeze" id="4-15">
                    <pos type="VB"/>
                    <lemma type="freeze"/>
                    <dep head="4-13" type="conj"/>
                </token>
                <token content="myself" id="4-16">
                    <pos type="PRP"/>
                    <lemma type="myself"/>
                    <dep head="4-13" type="dobj"/>
                </token>
                <token content="." id="4-17"/>
            </sentence>
            <sentence id="5">
                <token content="After" id="5-1">
                    <pos type="IN"/>
                    <lemma type="after"/>
                </token>
                <token content="the" id="5-2">
                    <pos type="DT"/>
                    <lemma type="the"/>
                </token>
                <token content="water" id="5-3">
                    <pos type="NN"/>
                    <lemma type="water"/>
                </token>
                <token content="is" id="5-4">
                    <pos type="VBZ"/>
                    <lemma type="be"/>
                </token>
